

FROM python:3.11-slim

WORKDIR /app


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


COPY pipeline.py .


ENV VALIDATION_SERVICE_URL=http://validation-service:8001
ENV MINIO_ENDPOINT=minio:9000


CMD ["python", "pipeline.py", "--scenario", "10"]
