// ~~styles de la page de resultat

export const styles = {
  wrapper: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
    paddingTop: "20px",
    paddingBottom: "40px",
  },
  header: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: "12px",
  },
  title: {
    margin: 0,
    fontSize: "1.5rem",
    color: "#111827",
  },
  fileChip: {
    margin: "6px 0 0",
    color: "#4b5563",
    fontSize: "0.9rem",
  },
  docTypeBadge: {
    backgroundColor: "#dbeafe",
    color: "#1d4ed8",
    padding: "6px 14px",
    borderRadius: "9999px",
    fontWeight: "700",
    fontSize: "0.85rem",
    whiteSpace: "nowrap",
    alignSelf: "center",
  },
  warningBox: {
    backgroundColor: "#fffbeb",
    border: "1px solid #fcd34d",
    borderRadius: "12px",
    padding: "16px 20px",
    color: "#92400e",
    fontSize: "0.9rem",
  },
  warningList: {
    margin: "8px 0 0",
    paddingLeft: "20px",
  },
  card: {
    backgroundColor: "white",
    borderRadius: "16px",
    padding: "28px",
    boxShadow: "0 4px 16px rgba(0,0,0,0.06)",
  },
  sectionTitle: {
    margin: "0 0 20px",
    fontSize: "1rem",
    color: "#374151",
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  fieldGrid: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  fieldRow: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    padding: "10px 14px",
    borderRadius: "10px",
    backgroundColor: "#f9fafb",
  },
  fieldIcon: {
    color: "#6b7280",
    flexShrink: 0,
  },
  fieldBody: {
    flex: 1,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "8px",
  },
  fieldLabel: {
    fontSize: "0.85rem",
    color: "#6b7280",
    fontWeight: "500",
    minWidth: "160px",
  },
  fieldInput: {
    flex: 1,
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
    padding: "6px 10px",
    fontSize: "0.9rem",
    color: "#111827",
    backgroundColor: "white",
    outline: "none",
    minWidth: "160px",
  },
  badge: {
    fontSize: "0.75rem",
    fontWeight: "700",
    padding: "2px 8px",
    borderRadius: "9999px",
    flexShrink: 0,
  },
  validateBtn: {
    border: "none",
    backgroundColor: "#1d4ed8",
    color: "white",
    padding: "14px 20px",
    borderRadius: "12px",
    fontWeight: "700",
    fontSize: "1rem",
    width: "100%",
  },
  validationBox: {
    borderRadius: "16px",
    padding: "20px 24px",
  },
  anomalieList: {
    margin: "4px 0 0",
    paddingLeft: "0",
    listStyle: "none",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  anomalieItem: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontSize: "0.88rem",
    color: "#374151",
  },
  gravityBadge: {
    padding: "2px 8px",
    borderRadius: "9999px",
    fontSize: "0.75rem",
    fontWeight: "700",
    textTransform: "uppercase",
    flexShrink: 0,
  },
  details: {
    backgroundColor: "white",
    borderRadius: "16px",
    padding: "16px 24px",
    boxShadow: "0 4px 16px rgba(0,0,0,0.06)",
  },
  summary: {
    cursor: "pointer",
    fontWeight: "600",
    color: "#374151",
    fontSize: "0.9rem",
    display: "flex",
    alignItems: "center",
  },
  pre: {
    marginTop: "16px",
    backgroundColor: "#0f172a",
    color: "#e2e8f0",
    padding: "16px",
    borderRadius: "10px",
    overflowX: "auto",
    fontSize: "0.8rem",
    lineHeight: "1.6",
  },
  emptyCard: {
    backgroundColor: "white",
    borderRadius: "16px",
    padding: "48px 32px",
    boxShadow: "0 4px 16px rgba(0,0,0,0.06)",
    textAlign: "center",
    maxWidth: "480px",
    margin: "40px auto",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  backBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    color: "#2563eb",
    fontWeight: "700",
    textDecoration: "none",
    fontSize: "0.95rem",
  },
};