// ~~styles de la page d upload

export const styles = {
  wrapper: {
    display: "flex",
    justifyContent: "center",
    paddingTop: "40px",
    paddingBottom: "40px",
  },
  card: {
    width: "100%",
    maxWidth: "640px",
    backgroundColor: "white",
    borderRadius: "20px",
    padding: "36px",
    boxShadow: "0 8px 32px rgba(0,0,0,0.08)",
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  cardHeader: {},
  title: {
    margin: "0 0 10px",
    fontSize: "1.5rem",
    color: "#111827",
  },
  subtitle: {
    margin: 0,
    color: "#6b7280",
    fontSize: "0.9rem",
    lineHeight: "1.6",
  },
  dropzone: {
    border: "2px dashed #d1d5db",
    borderRadius: "14px",
    padding: "32px 20px",
    textAlign: "center",
    cursor: "pointer",
    transition: "all 0.2s ease",
    backgroundColor: "#f9fafb",
    minHeight: "160px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  dropzoneDrag: {
    borderColor: "#2563eb",
    backgroundColor: "#eff6ff",
  },
  dropzoneSuccess: {
    borderColor: "#16a34a",
    backgroundColor: "#f0fdf4",
    cursor: "default",
    borderStyle: "solid",
  },
  dropzoneError: {
    borderColor: "#dc2626",
    backgroundColor: "#fef2f2",
  },
  dropHint: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "6px",
  },
  dropIcon: {
    fontSize: "2rem",
  },
  dropText: {
    margin: 0,
    color: "#374151",
    fontWeight: "600",
    fontSize: "0.95rem",
  },
  dropOr: {
    color: "#9ca3af",
    fontSize: "0.8rem",
  },
  dropBrowse: {
    color: "#2563eb",
    fontWeight: "700",
    fontSize: "0.9rem",
    textDecoration: "underline",
  },
  dropFormats: {
    color: "#9ca3af",
    fontSize: "0.75rem",
    marginTop: "4px",
  },
  filePreview: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    width: "100%",
    textAlign: "left",
  },
  fileIcon: {
    flexShrink: 0,
    color: "#6b7280",
  },
  fileInfo: {
    flex: 1,
    overflow: "hidden",
  },
  fileName: {
    display: "block",
    fontSize: "0.95rem",
    color: "#111827",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  fileSize: {
    fontSize: "0.8rem",
    color: "#6b7280",
  },
  removeBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    color: "#9ca3af",
    fontSize: "1rem",
    padding: "4px 8px",
    borderRadius: "6px",
    transition: "background 0.15s",
    flexShrink: 0,
  },
  errorBox: {
    backgroundColor: "#fef2f2",
    border: "1px solid #fca5a5",
    color: "#991b1b",
    padding: "12px 16px",
    borderRadius: "10px",
    fontSize: "0.85rem",
    display: "flex",
    gap: "8px",
    alignItems: "center",
  },
  button: {
    border: "none",
    backgroundColor: "#1d4ed8",
    color: "white",
    padding: "14px 20px",
    borderRadius: "12px",
    fontWeight: "700",
    fontSize: "1rem",
    width: "100%",
    transition: "background 0.15s, transform 0.1s",
  },
  btnInner: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
  },
  spinner: {
    display: "inline-block",
    width: "16px",
    height: "16px",
    border: "2px solid rgba(255,255,255,0.3)",
    borderTopColor: "white",
    borderRadius: "50%",
    animation: "spin 0.7s linear infinite",
  },
};